version: "3"
services:
    web:
        build:
            context: ./frontend
            dockerfile: Dockerfile

    backend:
        build:
            context: ./backend # Path to the directory containing your Go backend code
            dockerfile: Dockerfile # Path to the Dockerfile for the Go backend
        environment:
            - MONGOURI=${MONGOURI}
