version: "3"
services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            -3000:3000

    backend:
        build:
            context: ./backend # Path to the directory containing your Go backend code
            dockerfile: Dockerfile # Path to the Dockerfile for the Go backend
        environment:
            - MONGOURI=${MONGOURI}
        ports:
            -8000:8000

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            -80:80
