version: "3"
services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 1G

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        environment:
            - MONGOURI=${MONGOURI}
        ports:
            - "8000:8000"
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 1G

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 1G
