version: "3"
services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        environment:
            - ENVIRONMENT=${ENVIRONMENT}
        ports:
            - "3000:3000"

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        environment:
            - MONGOURI=${MONGOURI}
            - ENVIRONMENT=${ENVIRONMENT}
        ports:
            - "8000:8000"

    # nginx:
    #     build:
    #         context: ./nginx
    #         dockerfile: Dockerfile
    #     ports:
    #         - "80:80"
